### PR TITLE
returning response from first action of event

### PR DESCRIPTION
**Pull request by aleksanderwlodarczyk**

### CODE REVIEW

**Comment by naturallymitchell** [comment]
how does this work?

**Comment by naturallymitchell** [comment]
does the first action of the first event respond immediately, without running any other actions or events?

**Comment by aleksanderwlodarczyk** [comment]
The action output is assigned to lighttouch_response only when it is nil. So far it doesn't respond immediately.

**Comment by naturallymitchell** [comment]
ok. thx for explaining
let's continue discussing in https://github.com/foundpatterns/lighttouch-base/issues/62

**Pull request merged**
