### PR TITLE
Loaders simples separations code.

### PR DESCRIPTION
**Pull request by Hellfar**
It needs more changes.
This is just to see the diff obviously.

### CODE REVIEW

**Comment by Hellfar** [comment]
I made separations where it was obvious on loaders `rules`, `actions` and `events`.

**Comment by naturallymitchell** [comment]
wouldn't `function extract_yaml(modulepath)` make more sense than `extract_yaml = function(modulepath)`?

**Comment by Hellfar** [comment]
Oupsy, sorry for the delay...

To answer you @mitchtbaum, yeah it is better in my opinion too, but as you said it was temporary changes so I took the fastest copy/paste way ^^ .

But yes, in my opinion there's still a looooot to simplify, what I've done included.

**Comment by naturallymitchell** [comment]
It's cool, @Hellfar.  @Arnaz87 merged it.

Onwards to https://github.com/foundpatterns/lighttouch-base/issues/96

Please let me know if you think you'll have some time to work on it.

**Pull request merged**
