### PR TITLE
replace yaml with scl

### LINKED ISSUE #102: replace all uses of yaml with scl

### PR DESCRIPTION
**Pull request by naturallymitchell**
Fixes #102

### CODE REVIEW

**Comment by naturallymitchell** [comment]
@Hellfar what about `scl.from_table()`?  Don't we need to use a Tera template for now?

**Comment by Hellfar** [comment]
For now it seems to be working.

Still having the triple double quotes on the values of the fields when updated/created from the user interface (seems to not making any new issue though).
Look at this to have an idea why:
https://github.com/foundpatterns/torchbear/blob/master/src/bindings/text/scl.rs#L81-L95

If it is intended for fields to be multi-line then this is how it should remain.

**Comment by Hellfar** [comment]
Wait for this one, I have to fix the loaders as well.

**Comment by Arnaz87** [comment]
It would've been better if the `---` header was removed, that was a quirk of rust's yaml implementation, not really necessary or useful.

**Comment by Hellfar** [comment]
@Arnaz87, I am ok with whatever.
Just wanted to make it fixed.

We can always re-design it later ? I mean for now I was just focusing on behaving the same way everywhere and make it the way I was sure it would :) .

**Comment by Hellfar** [comment]
Arh, I wanted to fix the loaders as well on this one.

**Comment by Arnaz87** [comment]
Oh, mitchell asked me to merge these, what's wrong with the loaders?

**Comment by naturallymitchell** [comment]
actions, events, and rules having yaml headers?

**Comment by Arnaz87** [comment]
seems like it, i'm fixing those

**Pull request merged**
